name: redux_entity
description: Library for maintaining collections in a Redux store. Based on @ngrx/entity.
repository: https://github.com/careapp-inc/dart_redux_entity
version: 1.0.4
homepage: https://github.com/careapp-inc/dart_redux_entity

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  redux: ^5.0.0

dev_dependencies:
  mockito: ^5.0.2
  faker: ^2.0.0-rc.2
  test: ^1.16.0
  uuid: ^3.0.1
